#!/bin/bash
# Content deployment script
# Generated by Forge Agent

echo "📱 Deploying MarketingBot content..."

# This would integrate with Instagram/LinkedIn APIs
# For now, create manual posting guide

cat << 'GUIDE'
Manual Content Deployment Guide:

1. Access content queue:
   ls ~/.openclaw/workspace/marketingbot/content_queue/

2. Post to Instagram:
   - Copy content from JSON files
   - Use Instagram Creator Studio or Later.com
   - Schedule for optimal times (8am, 12pm, 6pm)

3. Post to LinkedIn:
   - Use professional tone
   - Tag relevant hashtags
   - Include call-to-action

4. Track engagement:
   - Monitor likes/comments
   - Respond to inquiries
   - Track lead conversions

GUIDE

echo "✅ Deployment guide created"
