# Stripe Integration for Booking Bot
# Generated by Forge Agent

import stripe
import os
from typing import Optional

class StripeBookingIntegration:
    """
    Handles booking deposits via Stripe
    """
    
    def __init__(self):
        # Use environment variable for security
        stripe.api_key = os.getenv('STRIPE_SECRET_KEY')
        
    def create_deposit_session(self, client_email: str, amount_cents: int = 5000) -> Optional[str]:
        """
        Create a Stripe checkout session for booking deposit
        Default: $50 deposit (5000 cents)
        """
        try:
            session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                line_items=[{
                    'price_data': {
                        'currency': 'sgd',
                        'product_data': {
                            'name': 'PT Session Deposit',
                            'description': 'Booking deposit for personal training session',
                        },
                        'unit_amount': amount_cents,
                    },
                    'quantity': 1,
                }],
                mode='payment',
                success_url='https://your-domain.com/success',
                cancel_url='https://your-domain.com/cancel',
                customer_email=client_email,
            )
            return session.url
        except Exception as e:
            print(f"Error creating session: {e}")
            return None

# Usage:
# stripe = StripeBookingIntegration()
# payment_url = stripe.create_deposit_session("client@email.com")
