#!/bin/bash
# Error analysis script
# Generated by Forge Agent

echo "🔍 Analyzing errors..."

LOGS=(
    "/tmp/fred_bot.log"
    "/tmp/watchdog_v3.log"
    "/tmp/coordinator.log"
)

for log in "${LOGS[@]}"; do
    if [ -f "$log" ]; then
        echo ""
        echo "=== $log ==="
        echo "Recent errors:"
        tail -50 "$log" | grep -E "(ERROR|Exception)" | tail -10
    fi
done
