#!/bin/bash
# Auto-generated restart script for Concierge Bot
# Generated by Forge Agent

echo "🔧 Restarting Concierge Bot..."

# Kill existing processes
pkill -f fred_pt_bot.py 2>/dev/null
sleep 2

# Start bot
cd /Users/fredericklaw/.openclaw/workspace/automation
nohup python3 fred_pt_bot.py > /tmp/fred_bot.log 2>&1 &
sleep 3

# Verify
if pgrep -f fred_pt_bot.py > /dev/null; then
    echo "✅ Concierge Bot restarted successfully"
    exit 0
else
    echo "❌ Failed to restart"
    exit 1
fi
