#!/bin/bash
# Disk cleanup script
# Generated by Forge Agent

echo "🧹 Cleaning disk space..."

# Clean old logs
echo "Removing old logs..."
find /tmp -name "*.log" -mtime +7 -delete 2>/dev/null
find ~/.openclaw/workspace -name "*.log" -mtime +7 -delete 2>/dev/null

# Clean Python cache
echo "Cleaning Python cache..."
find ~/.openclaw/workspace -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null

# Clean old screenshots
echo "Cleaning old screenshots..."
find /tmp -name "bolt_*.png" -mtime +1 -delete 2>/dev/null

echo "✅ Cleanup complete"
df -h /Users
